// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.22.2";

// src/lib/mcp/tools/get-about.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.2";
var ABOUT = {
  name: "Tran Le",
  location: "Atlanta, GA",
  headline: "Graduate Research Assistant and M.S. student in Data Science and Analytics at Georgia State University.",
  bio: [
    "I'm a Graduate Research Assistant and Master's student in Data Science and Analytics at Georgia State University, with a strong foundation in data analytics, machine learning, and healthcare data. My research focuses on leveraging advanced analytics to support clinical decision-making and patient outcomes.",
    "Currently, I collaborate with the Shepherd Center on healthcare analytics projects, applying machine learning techniques to stroke patient rehabilitation data. My goal is to bridge the gap between complex data and meaningful insights that drive real-world impact.",
    "I'm currently seeking a full-time position/internship starting in Fall 2026 (August) and a full-time role in December 2026 in Data Analytics, Data Science, and Data Engineering."
  ],
  education: [
    {
      degree: "M.S. in Data Science and Analytics",
      school: "Georgia State University",
      detail: "Concentration: Data Science in Business \u2022 GPA: 4.05",
      period: "Expected Dec 2026"
    },
    {
      degree: "B.B.A. in Computer Information Systems",
      school: "Georgia State University",
      detail: "Data Analytics Concentration \u2022 Magna Cum Laude",
      period: "May 2025"
    }
  ],
  values: [
    { title: "Analytical Rigor", description: "Methodical, evidence-based approaches in every analysis." },
    { title: "Reproducibility", description: "Transparent, well-documented work that can be validated and built upon." },
    { title: "Collaboration", description: "Working effectively with cross-functional teams to achieve shared goals." }
  ]
};
var get_about_default = defineTool({
  name: "get_about",
  title: "Get about",
  description: "Return a short bio, education history, and personal values for Tran Le.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(ABOUT, null, 2) }],
    structuredContent: ABOUT
  })
});

// src/lib/mcp/tools/list-skills.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.2";
var SKILLS = {
  categories: [
    {
      title: "Technical Skills",
      skills: [
        "SQL (Advanced)",
        "Python (pandas, NumPy, matplotlib)",
        "R",
        "NoSQL",
        "Machine Learning",
        "Deep Learning",
        "Gen AI",
        "Large Language Models (LLMs)",
        "Natural Language Processing (NLP)",
        "Clustering",
        "Data Pipelines",
        "Databricks",
        "Jupyter Notebook",
        "PyCharm",
        "MongoDB",
        "Power BI",
        "Tableau",
        "Excel (Pivot Tables, VLOOKUP)",
        "Data Visualization",
        "Data Architecture",
        "Statistics",
        "Transformation"
      ]
    },
    {
      title: "Data Wrangling & Preparation",
      skills: [
        "Data Cleaning & Preprocessing",
        "Missing Value Handling",
        "Outlier Detection",
        "Feature Engineering",
        "Data Normalization & Transformation",
        "Data Validation & Quality Checks",
        "ETL / ELT Pipelines"
      ]
    },
    {
      title: "Analytics & Tools",
      skills: [
        "Tableau",
        "Power BI",
        "Excel",
        "Databricks",
        "Jupyter Notebook",
        "PyCharm",
        "Statistical Analysis",
        "Quantitative Research"
      ]
    },
    {
      title: "Soft Skills",
      skills: [
        "Critical Thinking",
        "Decision-Making",
        "Communication Skills",
        "Problem-Solving",
        "Agility",
        "Learning Agility",
        "Analytical Thinking",
        "Data Storytelling",
        "Cross-Functional Collaboration",
        "Adaptability",
        "Attention to Detail",
        "Time Management",
        "Project Management",
        "Public Speaking",
        "Business Analyst"
      ]
    }
  ]
};
var list_skills_default = defineTool2({
  name: "list_skills",
  title: "List skills",
  description: "List Tran Le's skills grouped by category (technical, data wrangling, analytics tools, soft skills).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(SKILLS, null, 2) }],
    structuredContent: SKILLS
  })
});

// src/lib/mcp/tools/list-experience.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.2";
var EXPERIENCE = [
  {
    role: "Researcher Intern",
    organization: "Yamaha Motor Corporation, USA",
    period: "May 2026 \u2013 August 2026",
    current: false,
    highlights: [
      "Analyzed 100,000+ customer survey records with Excel, Python, SQL, and Power BI to identify trends, validate data quality, and support decisions.",
      "Collected 100,000+ records from the web using Python and structured them via crosstab data entry.",
      "Built data processing and reporting workflows that turned large-scale datasets into insights for cross-functional stakeholders.",
      "Used pandas and NumPy to clean, analyze, and visualize complex datasets while maintaining data integrity."
    ]
  },
  {
    role: "Data Science Researcher",
    organization: "FanDuel",
    period: "January 2026 \u2013 May 2026",
    current: false,
    highlights: [
      "Built an LLM-powered semantic retrieval and knowledge engineering pipeline over 8,000+ Confluence pages for ontology-driven data governance.",
      "Applied Sentence-BERT, TF-IDF, and cosine similarity to retrieve business context and generate standardized data definitions.",
      "Integrated documentation, schema metadata, and Databricks lineage into a unified Generative AI framework for governance and knowledge retrieval.",
      "Delivered production-ready ontology and enterprise data dictionary assets to FanDuel."
    ]
  },
  {
    role: "Graduate Research Assistant",
    organization: "Institute for Insight Department",
    period: "August 2025 \u2013 Present",
    current: true,
    highlights: [
      "Collaborating with faculty, peers, and industry partners (Shepherd Center, Truist Bank, Better Business Bureau) on real-world data science and ML projects.",
      "Performing data cleaning, EDA, and feature engineering using Python, SQL, RStudio, and AI tools.",
      "Building and evaluating predictive models using linear regression, classification, and ensemble methods.",
      "Contributing to technical documentation, code, and stakeholder presentations."
    ]
  },
  {
    role: "Data Analytics",
    organization: "Shepherd Center, Atlanta, Georgia",
    period: "August 2025 \u2013 December 2025",
    current: true,
    highlights: [
      "Analyzed stroke patient data to support precision rehabilitation and treatment planning.",
      "Applied linear regression, logistic regression, KNN, and Random Forest to identify effective treatment strategies.",
      "Performed data cleaning, EDA, feature engineering, and model evaluation in Python, SQL, and RStudio.",
      "Delivered technical documentation, reproducible code, and stakeholder presentations."
    ]
  },
  {
    role: "Research Assistant",
    organization: "Dr. Xinyu Fu, Computer Information System Department",
    period: "August 2024 \u2013 Present",
    current: true,
    highlights: [
      "Synthesized literature reviews into comprehensive reports across multiple research papers.",
      "Presented findings in written reports and oral presentations.",
      "Aligned research progress with goals via weekly meetings with supervisor and PhD candidates."
    ]
  },
  {
    role: "Learning Assistant",
    organization: "Mathematics and Statistics Department",
    period: "August 2023 \u2013 May 2025",
    current: false,
    highlights: [
      "Supported 1,000+ students in solving problems, completing assignments, and preparing for exams.",
      "Coordinated with professors weekly to identify student needs.",
      "Provided one-on-one and group tutoring, improving student performance."
    ]
  },
  {
    role: "Undergraduate Research Fellow",
    organization: "J. Mack Robinson College of Business",
    period: "January 2024 \u2013 April 2024",
    current: false,
    highlights: [
      "Conducted in-depth business research to enhance decision-making processes.",
      "Developed and refined research questions targeting real business challenges.",
      "Represented team in meetings, conferences, and workshops."
    ]
  }
];
var list_experience_default = defineTool3({
  name: "list_experience",
  title: "List experience",
  description: "List Tran Le's professional and research experience in reverse-chronological order.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(EXPERIENCE, null, 2) }],
    structuredContent: { experience: EXPERIENCE }
  })
});

// src/lib/mcp/tools/list-projects.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z } from "npm:zod@^4.4.3";
var PROJECTS = [
  {
    title: "Snowflake Sales & Forecasting Analytics Platform",
    period: "June 2026 \u2013 July 2026",
    description: "End-to-end analytics platform in Snowflake using advanced SQL and Snowpark Python to ingest, transform, validate, and forecast multi-year economic datasets from the Snowflake Marketplace. Evaluated ARIMA, SARIMAX, and ETS models using RMSE and built an interactive Streamlit dashboard.",
    tools: ["Snowflake", "SQL", "Snowpark Python", "Python", "Streamlit", "ARIMA", "SARIMAX", "ETS", "Time-Series Forecasting"],
    impact: "Automated end-to-end forecasting workflow and transformed raw economic data into actionable business insights."
  },
  {
    title: "Environmental Intelligence System",
    period: "January 2026 \u2013 May 2026",
    description: "Processed 500+ ESG and sustainability reports using Python-based document extraction and data pipelines. Built a Neo4j knowledge graph and ontology to connect environmental metrics, operational claims, and supporting evidence, then developed a Streamlit application for search and comparison.",
    tools: ["Python", "ESG", "Sustainability Analytics", "Document Extraction", "Data Pipelines", "Neo4j", "Knowledge Graph", "Ontology", "Streamlit"],
    impact: "Enabled users to search reports, compare companies, and investigate sustainability performance through a knowledge graph app."
  },
  {
    title: "Heart Attack Risk Prediction",
    period: "February 2026",
    description: "End-to-end ML model to predict heart attack risk, including data cleaning, preprocessing, EDA, class imbalance handling, and logistic regression classification. Presented at the AI & Analytics Conference poster competition.",
    tools: ["Python", "pandas", "numpy", "matplotlib", "scikit-learn", "Machine Learning", "Logistic Regression", "EDA"],
    impact: "Advanced to final presentation round at AI & Analytics Conference poster competition.",
    github: "https://github.com/htran2301/heart-disease",
    linkedin: "https://www.linkedin.com/feed/update/urn:li:activity:7433741349268402176/"
  },
  {
    title: "Healthcare Analytics \u2013 Shepherd Center",
    period: "August 2025 \u2013 December 2025",
    description: "Analyzed stroke patient data to support precision rehabilitation and treatment planning. Applied ML methods including linear regression, logistic regression, KNN, and Random Forest.",
    tools: ["Python", "SQL", "RStudio", "Machine Learning", "Linear Regression", "Logistic Regression", "KNN", "Random Forest", "Generative AI"],
    impact: "Delivered technical documentation, reproducible code, and stakeholder presentations for clinical decision-making."
  },
  {
    title: "Employee Attrition Prediction",
    period: "August 2025 \u2013 December 2025",
    description: "Supervised ML models to predict employee attrition using IBM HR Analytics data (1,470 employees), addressing class imbalance with SMOTE. Compared Logistic Regression, Decision Tree, Random Forest, SVM, and XGBoost.",
    tools: ["Python", "Machine Learning", "Logistic Regression", "Decision Tree", "Random Forest", "SVM", "XGBoost", "SMOTE", "Feature Engineering"],
    impact: "Identified key attrition drivers and translated model outputs into actionable retention insights.",
    github: "https://github.com/htran2301/employeeprediction_project"
  },
  {
    title: "Impact of Remote Work on Mental Health",
    period: "August 2025 \u2013 December 2025",
    description: "Analyzed a 5,000-record global workforce dataset to examine how remote work influences mental health, stress, work\u2013life balance, and productivity. Performed cleaning, EDA, and visualization.",
    tools: ["Python", "Data Visualization", "EDA", "pandas", "matplotlib", "seaborn"],
    impact: "Uncovered global and role-specific mental health trends and demonstrated visual analytics for evidence-based policy.",
    github: "https://github.com/htran2301/remotework_project"
  },
  {
    title: "Healthcare Monitoring Systems",
    period: "August 2025 \u2013 December 2025",
    description: "Built a healthcare monitoring system in Databricks using SQL over 1,000+ synthetic patient records with a focus on Type 2 Diabetes. Delivered a dashboard for high-risk identification and overdue follow-ups.",
    tools: ["Databricks", "SQL", "Data Analytics", "Dashboard", "Healthcare Data"],
    impact: "Enabled data-driven identification of high-risk patients and overdue follow-ups.",
    github: "https://github.com/htran2301/healthcaresystems_project"
  },
  {
    title: "Capstone Site 2.0 Website \u2013 Team Lead",
    period: "January 2025 \u2013 May 2025",
    description: "Led a team of 3, collaborating with faculty, alumni, and companies to build 80% of a website for CIS undergraduates. Managed scope, timelines, tasks, and documentation.",
    tools: ["Figma", "Webflow", "Google Sites", "UI/UX", "Smartsheet", "Project Management"],
    impact: "Delivered a user-friendly platform for CIS students."
  },
  {
    title: "Fraudulent Job Post Detection",
    period: "August 2024 \u2013 December 2024",
    description: "Team ML pipeline in R analyzing 17,000+ job postings with 17 features to detect fraud. Compared multiple models after data cleaning and feature engineering.",
    tools: ["R", "Logistic Regression", "KNN", "Random Forest", "Feature Engineering"],
    impact: "98% accuracy and 97% balanced accuracy with Random Forest."
  },
  {
    title: "Youth Entertainment Hack-A-Ton Project",
    period: "2024",
    description: "Independently built a youth entertainment website prototype during a Hack-A-Ton after team challenges.",
    tools: ["Google Sites", "Web Development", "UI/UX"],
    impact: "Built a complete prototype independently under pressure.",
    website: "https://sites.google.com/view/youthentertainment/home"
  }
];
var RESEARCH = {
  title: "Talk to Me: A Preliminary Review on the Evolution and Impact of Emotional AI",
  venue: "AMCIS 2025 \u2022 TREO Talk",
  url: "https://aisel.aisnet.org/treos_amcis2025/194/"
};
var list_projects_default = defineTool4({
  name: "list_projects",
  title: "List projects",
  description: "List Tran Le's data science, analytics, and ML projects. Optionally filter with a case-insensitive substring against title, description, or tools.",
  inputSchema: {
    query: z.string().trim().min(1).optional().describe("Optional case-insensitive substring filter (title, description, tools).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ query }) => {
    const q = query?.toLowerCase();
    const filtered = q ? PROJECTS.filter((p) => {
      const haystack = [p.title, p.description, ...p.tools].join(" ").toLowerCase();
      return haystack.includes(q);
    }) : PROJECTS;
    const payload = { count: filtered.length, projects: filtered, research: RESEARCH };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/list-awards.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.22.2";
var AWARDS = [
  { title: "AMCIS 2025 Reviewer", institution: "Americas Conference on Information Systems", period: "August 2025", type: "certificate" },
  { title: "Delta Analytics Scholars", institution: "Georgia State University Foundation", period: "Spring 2026", type: "scholarship" },
  { title: "Outstanding Work Recognition", institution: "Shepherd Center", period: "December 2025", type: "certificate" },
  { title: "Fall 2025 Analytics Sprint", institution: "Georgia State University & Shepherd Center", period: "December 2025", type: "certificate" },
  { title: "WIT Campus Graduate", institution: "Women in Technology", period: "2025", type: "certificate" },
  { title: "Undergraduate Research Fellow", institution: "J. Mack Robinson College of Business", period: "Spring 2024", type: "certificate" },
  { title: "Dean's List", institution: "Georgia State University", period: "Fall 2024, Spring 2023", type: "dean" },
  { title: "President's List", institution: "Georgia State University", period: "Spring 2025, Summer 2024", type: "president" }
];
var list_awards_default = defineTool5({
  name: "list_awards",
  title: "List awards",
  description: "List Tran Le's academic and professional awards, honors, and certificates.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(AWARDS, null, 2) }],
    structuredContent: { awards: AWARDS }
  })
});

// src/lib/mcp/tools/get-contact.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.22.2";
var CONTACT = {
  name: "Tran Le",
  email: "tranle2301.01@gmail.com",
  phone: "(206) 209-8181",
  location: "Atlanta, GA",
  linkedin: "https://www.linkedin.com/in/tranle2301",
  github: "https://github.com/htran2301",
  portfolio: "https://tranleportfolio.lovable.app",
  seeking: "A full-time position/internship starting in Fall 2026 (August) and a full-time role in December 2026 in Data Analytics, Data Science, and Data Engineering."
};
var get_contact_default = defineTool6({
  name: "get_contact",
  title: "Get contact info",
  description: "Return Tran Le's public contact information and current job-search focus.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(CONTACT, null, 2) }],
    structuredContent: CONTACT
  })
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "tran-le-portfolio-mcp",
  title: "Tran Le Portfolio",
  version: "0.1.0",
  instructions: "Public tools that expose Tran Le's data science portfolio: about/bio, skills, experience, projects, awards, and contact information. All data is already public on tranleportfolio.lovable.app. Use list_projects with an optional query to filter by keyword.",
  tools: [get_about_default, list_skills_default, list_experience_default, list_projects_default, list_awards_default, get_contact_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
